import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

import NavBar from './components/NavBar/NavBar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <div>
        <NavBar />
      </div>

      <body className={inter.className}>{children}</body>
    </html>
  );
}
